export const selectionUser = {
  email: true,
  address: true,
  companyName: true,
  createdAt: true,
  description: true,
  facebookLink: true,
  image: true,
  instagramLink: true,
  linkedInLink: true,
  mainLink: true,
  twitterLink: true,
  userName: true,
  verified: true,
  verificationDate: true,
  verificationLink: true,
  role: true,
}

export const selectionNFT = {
  createdAt: true,
  name: true,
  blockchainType: true,
  fileUrl: true,
  multimediaFile: true,
  price: true,
  isOnMarket: true,
  isMetadataFrozen: true,
  tokenId: true,
  itemId: true,
  startSaleDate: true,
  endSaleDate: true,
  startLeaseDate: true,
  endLeaseDate: true,
  saleType: true,
  collectibleCategory: true,
  productKeyRealLifeAssetCategory: true,
  productKeyVirtualAssetCategory: true,
  isSensitiveContent: true,
  properties: true,
  reviews: true,
  ercType: true,
  like: true,
}

export const selectionCollection = {
  image: true,
  description: true,
  createdAt: true,
  name: true,
}
