export const selectionUser = {
  email: true,
  address: true,
  companyName: true,
  createdAt: true,
  description: true,
  facebookLink: true,
  image: true,
  instagramLink: true,
  linkedInLink: true,
  mainLink: true,
  twitterLink: true,
  userName: true,
  verified: true,
  verificationDate: true,
  role: true,
  likedNfts: true,
  cartNfts: true,
}

export const selectionNFT = {
  createdAt: true,
  name: true,
  blockchainType: true,
  fileUrl: true,
  multimediaFileUrl: true,
  price: true,
  isOnSale: true,
  isOnLease: true,
  isOnAuction: true,
  isMetadataFrozen: true,
  isSensitiveContent: true,
  tokenId: true,
  itemId: true,
  startSaleDate: true,
  endSaleDate: true,
  saleType: true,
  collectibleCategory: true,
  productKeyAccessTokenCategory: true,
  productKeyVirtualAssetCategory: true,
  ercType: true,
  likes: true,
  descriptions: true,
  propertiesKey: true,
  propertiesValue: true,
  imagesKey: true,
  imagesValue: true,
  levelsKey: true,
  levelsValueNum: true,
  levelsValueDen: true,
}

export const selectionReview = {
  rating: true,
  comment: true,
  title: true,
}

export const selectionCollection = {
  image: true,
  description: true,
  createdAt: true,
  name: true,
  isNameModified: true,
}
